### ISSUE TITLE
Out of Town

### ISSUE THREAD

**Issue by moonmeister** [moonmeister/xo-install-script#13]
I'm leaving civilization for ~5 months to go hike the Pacific Crest Trail from mexico to Canada. I will have occasional email access but it will not be my priority to answer Github issues and I will be unable to make any code changes. If something pressing comes up I'll do my best to be available to discuss and accept a PR but due to lack of connectivity it might take time. 

Thanks for your understanding. I hope you find this project useful as I have.

**Comment by olivierlambert** [comment]
Hey @moonmeister enjoy your trip!

**Comment by moonmeister** [comment]
I'm back!
