### ISSUE TITLE
Feature request: Check for nfs-common

### ISSUE THREAD

**Issue by astrugatch** [moonmeister/xo-install-script#14]
NFS shares used by remote require nfs to be installed on the XOA host. Can you add a check to make sure its there and an apt-get / yum if its not found?

Sorry to hit you up when you only just got back. Hope you enjoyed the trip.

**Comment by moonmeister** [comment]
Hey, yes, i could swear it already did that cause I've run into the issue, but I guess I'm wrong if you've had issues. I'll look into it and let you know.

**Comment by moonmeister** [comment]
just added it to the dependency installation. fyi, this only supports debian currently which uses apt-get. yum is for RH/CentOS which are not currently supported. latest push to master will have the update.
