### ISSUE TITLE
Update to 5.29 broken

### ISSUE THREAD

**Issue by astrugatch** [moonmeister/xo-install-script#15]
did a git pull on this repo,
Attempted ./xoctl.sh update and the install failed
Attaching the ssh output from my session.

[20181031_131856.SSH.w0t0p0.A93468A2-BD6F-4AA8-AB98-491E386F0B3D.1704.223103336.log](https://github.com/moonmeister/xo-install-script/files/2535616/20181031_131856.SSH.w0t0p0.A93468A2-BD6F-4AA8-AB98-491E386F0B3D.1704.223103336.log)

**Comment by pflaugh** [comment]
Tested as well. Got the same output as above. Using v0.3.1-alpha version of the script on fully patched Ubuntu 16.04

**Comment by pflaugh** [comment]
Things seem to fall apart during the XO Yarn install.

``Xen Orchestra new version: xo-web-v5.29.1
re-building Xen Orchestra
yarn install v1.12.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[6/9] ? leveldown
[-/9] ? waiting...
[-/9] ? waiting...
[-/9] ? waiting...
**error /opt/xen-orchestra/node_modules/level-party/node_modules/leveldown: Command failed.**
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /opt/xen-orchestra/node_modules/level-party/node_modules/leveldown

**Comment by pflaugh** [comment]
This is starting to look like an issue with Node.

**Comment by pflaugh** [comment]
I figured it out! The script is updating Node past where Vates/XenOrchestra recommends. They recommend v8. The script is updating it to v10 i think (I have already reverted back to my pre-update snapshot)

Running node -v prior to the script verified I was on v8.12.0

I am able to confirm this by building manually and everything completed without error.

**Comment by moonmeister** [comment]
The script should install the node lts...which last I checked is version
8.12. I'll look into this soon, your welcome to submit a PR with a fix.

AJ

**Comment by moonmeister** [comment]
Ok. So n is installing the LTS...but we have two active LTS versions so it's installing node 10. The easy fix is to just have install the latest version of 8....but when XO finally starts supporting 10 then it'll break again.

Any one have suggestions on getting around this? like in the XO package.json is the supported node version defined?

**Comment by moonmeister** [comment]
@olivierlambert Would you take a PR for adding the required node version to the `package.json`? This would help with stabilizing builds for people building from the source and anyone trying to script this.

NPM docs here:
https://docs.npmjs.com/files/package.json#engines
