### ISSUE TITLE
/usr/local/bin/xoctl.sh install : ./sample.config.yaml ( file not found )

### ISSUE THREAD

**Issue by dbmello75** [moonmeister/xo-install-script#16]
I'm trying to install it in Debian 10. 
I'm getting a file not found in this file: ./sample.config.yaml

**Comment by olivierlambert** [comment]
This is the risk of using 3rd party scripts to install Xen Orchestra: some aren't updated anymore.

Please stick on [XO official documentation](https://xen-orchestra.com/docs/installation.html#from-the-sources) to install it, and report on the forum if you have any issue with it. Really, it's not that hard to install it by yourself :)

**Comment by astrugatch** [comment]
If you think you NEED to use a script
Check out Jarli01 on github. This is currently working for me on Ubuntu18.04 but again ymmv with a script.

**Comment by dbmello75** [comment]
Thank you. I should've paid attention to the last commit date.

**Comment by dbmello75** [comment]
closing
