### ISSUE TITLE
Hardcodeed "sudo" in install.sh cancels install in Debian Jessie 8.9

### ISSUE THREAD

**Issue by bwielsch** [moonmeister/xo-install-script#6]
Hi, great job. I love it.
May be I can help to improve it a little bit. On the whole your script is working fine.
It seems that the hardcoded sudo prefixes within the commands in your install.sh will abort installation when you do not use Ubuntu.
As workaround for me I've deleted all the sudo prefixes within the script and afterward everything works fine:-)

Regards Bernhard

**Comment by moonmeister** [comment]
Thanks for pointing those out. The sudo check at the beginning is designed to make so I didn't need those declared ones. I think in updating the code I missed those sudos. Thanks.
